
import pandas as pd

dominios = {
        "Estudiantes": [
            "Admisión (Postulantes)",
            "Oferta de carreras y programas",
            "Deportes y actividad física",
            "Equidad e inclusión",
            "Beneficios estudiantiles (Finanzas)",
            "Asuntos comunitarios",
            "Salud estudiantil",
            "Matrícula",
            "Inscripción de ramos",
            "Historial académico",
            "Datos Personales",
            "Egresados y titulados"
        ],
        "Recursos humanos": [
            "Bienestar del personal",
            "Reclutamiento",
            "Evaluación de desempeño",
            "Capacitación",
            "Prevención de riesgos",
            "Desvinculación y retiro",
            "Contrataciones",
            "Situaciones funcionarias y licencias",
            "Datos Personales",
            "Dotación"
        ],
        "Investigación y desarrollo académico": [
            "Premios",
            "Publicaciones",
            "Proyectos",
            "Fondos concursables",
            "Creación artística",
            "Innovación",
            "Desempeño académico",
            "Datos Personales",
            "Gestión (comisión, senado, participaciones)"
        ],
        "Docencia": [
            "Calendario académico",
            "Asignaturas",
            "Programas",
            "Datos Personales",
            "Evaluación del docente"
        ],
        "Finanzas": [
            "Contabilidad",
            "Cobranza",
            "Compras",
            "Ventas",
            "Remuneración del personal",
            "Aranceles universitarios",
            "Crédito universitario",
            "Presupuesto",
            "Datos Personales",
            "Tesorería y gestión de caja"
        ],
        "Infraestructura y servicios": [
            "Obras",
            "Proyectos de obras",
            "Propiedades",
            "Vehículos",
            "Espacios internos (Salas de clase)",
            "Espacios externos (Estacionamientos, canchas)",
            "Biblioteca",
            "TUI",
            "Gestión energética",
            "Datos Personales",
            "Gestión de eventos"
        ],
        "Extensión": [
            "Red de salud",
            "Medios de comunicación",
            "Publicaciones",
            "Cuerpos artísticos",
            "Asistencia jurídica",
            "Conciertos, teatros y cine",
            "Museos y salas de exposiciones",
            "Sitios culturales y conmemorativos",
            "Datos Personales",
            "Iniciativas de extensión y vinculación"
        ]
        }

# Datos de ejemplo para cada subdominio
data_catalog = {
    "Datos Personales": pd.DataFrame({
    "Unnamed: 0": [
    "Identificador de la persona",
    "Nombre",
    "Apellido Primario",
    "Apellido secundario",
    "Nombre social",
    "Sexo",
    "Género",
    "Fecha de nacimiento",
    "Fecha de defunción",
    "Nacionalidad",
    "Dirección",
    "Teléfono",
    "Estado civil",
    "Ascendencia étnica",
    "Cuenta de pasaporte"
],
"Descripción": [
    "Identificador principal de la persona.",
    "NOMBRE LEGAL DE LA PERSONA.",
    "Apellido primario",
    "Apellido secundario de la persona.",
    "Nombre social de la persona",
    "Corresponde al sexo registral de la persona; Puede ser Hombre, mujer, NO BINARIO. Valor correspondiente al que aparece en el documento de identificación legal.",
    "Masculino\nFemenino\nTrans Masculino\nTrans mefenino\nNo binario\nOTros\n\n",
    "Fecha de nacimiento de la persona",
    "Fecha de defunción de la persona",
    "Corresponde a la nacionalidad de la persona. En caso que tenga más de una nacionalidad se debe indicar la principal.",
    "Corresponde a la o las dirección de la persona.\n",
    "Corresponde al o los teléfonos de la persona.",
    "Estado civil de la persona. . Valor correspondiente al registrado en el SRCEI.",
    "Coresponde a la ascencdencia étnica de la persona.",
    "Es la cuenta de acceso única a los distintos servicios en línea que entrega la Universidad de Chile"
],
"Situación actual": [
    "(PERSONA - UCHDB) Identificador legal\n(DATOS_PERSONALES - WEB) - INDIV_ID\n(INDIVIDUO - SUG) ID\n(DOTACION - SUG) RUT",
    "(PERSONA - UCHDB) Nombres\n(DATOS_PERSONALES - WEB) Nombre \n(INDIVIDUO - SUG) Nombres \n(DOTACION - SUG) Nombres",
    "(PERSONA - UCHDB) Paterno\n(DATOS_PERSONALES - WEB) Paterno\n(INDIVIDUO - SUG) Paterno \n(DOTACION - SUG) Paterno",
    "(PERSONA - UCHDB) Materno\n(DATOS_PERSONALES - WEB) Materno\n(INDIVIDUO - SUG) Materno \n(DOTACION - SUG) Materno",
    "(PERSONA - UCHDB) Nombre_social\n(DATOS_PERSONALES - WEB) Nombre\n(INDIVIDUO - SUG) \n(DOTACION - SUG) ",
    "(PERSONA - UCHDB) Genero\n(DATOS_PERSONALES - WEB) SEXO\n(INDIVIDUO - SUG) SEXO\n(DOTACION - SUG) SEXO",
    " ",
    "(PERSONA - UCHDB) FECHA_NACIMIENTO\n(DATOS_PERSONALES - WEB) F_NACIMIENTO\n(INDIVIDUO - SUG) FECHA_NACIM \n(DOTACION - SUG) FECH_NAC",
    "(PERSONA - UCHDB) FECHA_DEFUNCION \n(DATOS_PERSONALES - WEB) \n(INDIVIDUO - SUG) \n(DOTACION - SUG) FECH_FALLECIMIENTO",
    "(PERSONA - UCHDB) ID_NACIONALIDAD\n\n(DATOS_PERSONALES - WEB) NACIONALIDAD \n\n(INDIVIDUO)\n\n1. TABLA: SUG.INDIVIDUO, Columnas: PAIS \n2. TABLA: NACIONALIDADES_INDIV, Columnas: NAC_ID (asociado a Individuo para estudiantes)\n\n(DOTACION - SUG) NACION ",
    "(PERSONA - UCHDB) \n1. TABLA: DIRECCIONES.DIRECCION, Columnas: CALLE_LINEA_1 + NUMERO + BLOCK + DEPARTAMENTO + MUNICIPIO + CIUDAD + CODIGO POSTAL\n\n(DATOS_PERSONALES -WEB) \n\n(INDIVIDUO)\n\n1. TABLA: SUG.INDIVIDUO, Columnas: DIRECCION + CIUDAD (Solamente AUGE) \n2. TABLA: SUG.DIRECCIONES, Columnas: CALLE + NUMERO + DEPTO + POBLACION-VILLA + COMUNA + CIUDAD (Para estudiantes)\n3. TABLA: SUG.SUG_DIRECCIONES\n\n(DOTACION)\n\n1. TABLA: SUG.DOTACION, Columnas: DIRECCION + DIRECCION_NUMERO + RESTO_DIRECCION + COMUNA + CIUDAD (Solamente AUGE) \n2. TABLA: SUG.SUG_DIRECCIONES\n",
    "(PERSONA - UCHDB) \n(DATOS_PERSONALES -WEB) FONO \n(INDIVIDUO - SUG) TELEFONO\n(DOTACION - SUG) FONO",
    "(PERSONA - UCHDB) \n(DATOS_PERSONALES -WEB) ESTADO_CIVIL \n(INDIVIDUO - SUG) ESCI_ID\n(DOTACION - SUG) EST_CIVIL",
    "(PERSONA - UCHDB) ID_ASC_ETNICA \n(DATOS_PERSONALES -WEB)\n(INDIVIDUO - SUG)\n(DOTACION - SUG) TIPO_PUEBLO_ORIG ",
    "(PERSONA - UCHDB)\n(DATOS_PERSONALES -WEB) USERNAME \n(INDIVIDUO - SUG)\n(DOTACION - SUG)"
],
"Lista de valores (Actual)": [
    "No aplica",
    "No aplica",
    "No aplica",
    "No aplica",
    "No aplica",
    "(UCHDB) MASCULINO - FEMENINO - NO BINARIO\n(WEB) 0-MASCULINO 1-FEMENINO\n(INDIVIDUO) 1-MASCULINO 2-FEMENINO\n(DOTACION) 0-FEMENINO 1-MASCULINO ",
    " ",
    "No aplica",
    "No aplica",
    " ",
    "(DOTACION) Comuna y Ciudad son texto libre\n(INDIVIDUO) Ciudad es texto libre\n(DIRECCIONES_INDIV) Lista de valores en tablas comunas y ciudades",
    "No aplica",
    "\n(PERSONA - UCHDB) 1-SOLTERO/A 2-CASADO/A 3-Separado legalmente 4-Separado de Hecho 5-Viudo (a) 6-Conviviente 9-Sin Informacion 8-Otro Estado 10-Divorciado(a) 7-Conviviente Civil\n\n(DATOS_PERSONALES -WEB) 0001-CASADO/A 0002-SOLTERO/A 0003-VIUDO/A 0004-DIVORCIADO/A 0005-DIVORCIADO/A 0006-PENDIENTE\n\n(INDIVIDUO - SUG) 1-SOLTERO/A 2-CASADO/A 3-Separado legalmente 4-Separado de Hecho 5-Viudo (a) 6-Conviviente 8-Sin Informacion 9-Otro Estado 14-Divorciado(a) 15-Conviviente Civil\n\n(DOTACION - SUG) 0001-CASADO/A 0002-SOLTERO/A 0003-VIUDO/A 0004-PENDIENTE 0005-DIVORCIADO/A\n",
    "\n(PERSONA - UCHDB) Ver link\n\n(DATOS_PERSONALES -WEB)\n\n(INDIVIDUO - SUG)\n\n(DOTACION - SUG) 000-No Informado 001-KAWASHKAR o ALACALUFE 002-ATACAMEÑA 003-AYMARA 004-COLLA 005-DIAGUITA 006-MAPUCHE 999-OTRAS ASCENDENCIAS",
    "No aplica"
],
"Standard": [
    "En el caso que el identificador legal sea el RUT, éste debe ser registrado completo sin puntos, y dígito verificador en mayúsculas. Para el caso de pasaportes, debe comenzar con la letra P y 0 para cualquier usuario chileno.",
    "La primera letra de la palabra deberá estar en\nmayúscula y el resto en minuscula.\nEn el caso de poseer mas de uno, como se usa en chile, deben todos ir aqui separados por espacio o igual a como se encuentra registrado en el SRCEI.",
    "La primera letra de la palabra deberá estar en\nmayúscula y el resto en minuscula.",
    "La primera letra de la palabra deberá estar en\nmayúscula y el resto en minuscula.",
    "La primera letra de la palabra deberá estar en mayúscula y el resto en minúscula..",
    " ",
    " ",
    "DD/MM/YYYY.",
    "DD/MM/YYYY.",
    "MASCULINO - FEMENINO - NO BINARIO",
    "Para datos de este tipo, se seguir ́a la siguiente estructura \n- Calle linea 1, Numero, Block, Departamento Cuidad, Código postal, Referencia\nDonde:\nCalle corresponde al nombre de la calle\nNúmero corresponde al numeral en la calle\nBlock se indica en función de la direccion si es que aplica. Se refiere a torres,\nblocks en conjunto de departamentos, etc...\nDepartamento corresponde al número o letra del departamento de la direc-\nción indicada.\nCiudad corresponde a la respectiva cuidad de la ubicación\nCódigo postal asociado a la localización\nReferencia para ayudar a la localización",
    "Se debe registrar el número considerando el código de área y/o país.",
    "1-SOLTERO/A \n2-CASADO/A \n3-Separado legalmente \n4-Separado de Hecho \n5-Viudo (a) \n6-Conviviente \n9-Sin Informacion \n8-Otro Estado \n10-Divorciado(a) \n7-Conviviente Civil",
    "1-No Informado \n2-KAWASHKAR o ALACALUFE \n3-ATACAMEÑA \n4-AYMARA \n5-COLLA \n6-DIAGUITA \n7-MAPUCHE \n8-QUECHUA \n9-RAPA NUI \n10-YÁMANA o YAGÁN \n11-OTRAS ASCENDENCIAS \n12-AFRODESCENDIENTE CHILENO \n13-CHANGO",
    "Se sugiere sea nombre.ap_primario"
],
"Lista de valores (Estándar)": [
    "No aplica",
    "No aplica",
    "No aplica",
    "No aplica",
    " ",
    "MASCULINO - FEMENINO - NO BINARIO\n",
    " ",
    " ",
    " ",
    "Dato referencial de paises",
    "Lista de valores para comunas en referencia direcciones.municipio\nLista de valores para provincias en referencia direcciones.provincia\nLista de valores para comunas en referencia direcciones.comunas\nLista de valores para paises en referencia direcciones.pais",
    " ",
    "Dato referencial de estados civiles en Chile:\nSoltero/a\nCasado/a\nViudo/a\nDivorciado/a\nSeparado/a\nSeparado/a de hecho\nConviviente\nConviviente civil (Acuerdo de uni ́on civil)\nOtro estado",
    "Dato referencial de ascendencia étnica",
    ""
    
],
"Reglas de transformación": [
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " ",
    " "
    
],
"Reglas de validación": [
    "Cabe señalar que una persona puede tener multiples identificadores (RUT, Pasaporte, numero identidad en su pais, etc..), pero para efectos registro siempre se debe marcar sólo uno principal.\nFormato: Alfanumérico (140)",
    "Primera letra en mayúscula y/o Identico a cédula de identidad nacional o Pasaporte\n\nFormato: Alfanumérico (25)",
    "Primera letra en mayúscula y/o Identico a cédula de identidad nacional o Pasaporte\nFormato: Alfanumérico (25)",
    "Primera letra en mayúscula y/o Identico a cédula de identidad nacional o Pasaporte.\nPuede ser valor nulo\nFormato: Alfanumérico (25)",
    "Debe ser informado el informado por la Dirección de Igualdad de Género \n(DIGEN), Rectoría",
    "Sólo lista de valores\nFormato: Alfanumérico (10)",
    " ",
    "Fecha debe ser menor o igual a fecha actual\nNo debe incluir hora\nFormato: Fecha (Date)",
    "Fecha puede ser nula y si tienen valor debe ser menor o igual a fecha actual y debe ser mayor a la fecha de nacimiento\nNo debe incluir hora\nFormato: Fecha (Date)",
    "Sólo lista de valores\nFormato: Alfanumérico (10)",
    " ",
    "El núumero de teléfono no debe contener menos de 5 dígitos, ni uno con más de 20 d ́ígitos, además de sólo caracteres numéricos.",
    "Sólo lista de valores",
    "Lista de valores o valor nulo en caso de no identificarse con ninguna ascendencia.",
    "Largo mínimo 8 caracteres"
],
"Fuentes de consumo de aplicaciones": [
    "API PERSONA (PLATAFORMA HABILITANTE)",
    "API PERSONA (PLATAFORMA HABILITANTE)",
    "API PERSONA (PLATAFORMA HABILITANTE)",
    "API PERSONA (PLATAFORMA HABILITANTE)",
    "API PERSONA (PLATAFORMA HABILITANTE)",
    "API PERSONA (PLATAFORMA HABILITANTE)",
    " ",
    "API PERSONA (PLATAFORMA HABILITANTE)",
    "API PERSONA (PLATAFORMA HABILITANTE)",
    "API PERSONA (PLATAFORMA HABILITANTE)",
    "API PERSONA (PLATAFORMA HABILITANTE)",
    "API PERSONA (PLATAFORMA HABILITANTE)",
    "API PERSONA (PLATAFORMA HABILITANTE)",
    "API PERSONA (PLATAFORMA HABILITANTE)",
    "API PERSONAS (PLATAFORMA HABILITANTE)"
],
"Fuentes de consumo de gestión": [
    "Cubo persona (U-Datos)",
    "Cubo persona (U-Datos)",
    "Cubo persona (U-Datos)",
    "Cubo persona (U-Datos)",
    "Cubo persona (U-Datos)",
    "Cubo persona (U-Datos)",
    " ",
    "Cubo persona (U-Datos)",
    "Cubo persona (U-Datos)",
    "Cubo persona (U-Datos)",
    "Cubo persona (U-Datos)",
    "Cubo persona (U-Datos)",
    "Cubo persona (U-Datos)",
    "Cubo persona (U-Datos)",
    "Cubo persona (U-Datos)"
]
})
}